[package]
name = "fourad"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.4"
regex = "1.5.4"
thiserror = "1.0.29"
